### ISSUE TITLE
Is there a space at the start of the title?

### ISSUE THREAD

**Issue by gep13** [RickStrahl/Snippets-MarkdownMonster-Addin#2]
Am I seeing things:

![image](https://cloud.githubusercontent.com/assets/1271146/22146517/d069b93e-defc-11e6-88fb-12f6b03b76bb.png)

Or is there an extra character at the start of `SnippetsAddin`?

**Comment by RickStrahl** [comment]
Yup. also in the snippet name. Looks like a R# refactor gone wrong :-)

Fixed in 0.2.4

**Comment by gep13** [comment]
Sweet, thanks for fixing!

**Comment by gep13** [comment]
@RickStrahl actually, no.  Something still not right here for me 😢 

I have 0.2.4 installed, but I am still seeing the extra space at the start.  Could this be related to the other issue that I am seeing with the `~` not working?

**Comment by gep13** [comment]
![image](https://cloud.githubusercontent.com/assets/1271146/22267528/03088e38-e27c-11e6-972f-8f8e8be84045.png)

![image](https://cloud.githubusercontent.com/assets/1271146/22267543/10fe246c-e27c-11e6-92f2-fb773482952c.png)

**Comment by RickStrahl** [comment]
Yeah I think so.

Can you go and nuke the Addins folder of any snippets related addins. Do you see multiple icons for the Snippets addin on the toolbar? I think the problem is probably that you built a dev version which output the old folder name which doubles up the addin. At that point it's a crap shoot which version gets used.

See other posts for locations to check.

Also make sure the old `Program Files\Markdown Monster` location is gone. The new location should be the 32 bit `Program Files (x86)\Markdown Monster` folder. If there's anything left in the old folder nuke that.

**Comment by gep13** [comment]
@RickStrahl ok, I am at a complete loss.

I have completely uninstalled markdownmonster, removed all the folders that have been suggested, re-installed MM (1.1.20) from Chocolatey, re-installed the snippets addin, and both issues still seem to be there, i.e.:

* extra space at the start of the menu item
* ~ not resolving

The only thing that I have left to try is to NOT use Chocolatey to do the install, to see if that doesn't anything different.  Are you using Chocolatey to install on your machine?

**Comment by RickStrahl** [comment]
No the choco install (unless you use the portable one) uses the same installer and installs into the same place.

The only other thing I didn't mention is perhaps the portable install is getting in the way? Check the ProgramData\Chocolatey\libs\MarkdownMonster folder and see if that's there? And the addin installed there?

Does MM say it's running 1.1.20?

Just for clarification - the addin locations are resolved like this:

* `Addins` folder in Install folder (for built-in addins)
* `Addins` folder in `%appdata%\Markdown Monster` folder

If you can't figure it out, may be ping me on Skype and I can take a look via screen share. I'd like to see what would cause this madness myself. @Rickstrahl
