### ISSUE TITLE
Ability to position cursor after snippet addition

### ISSUE THREAD

**Issue by gep13** [RickStrahl/Snippets-MarkdownMonster-Addin#3]
After adding the snippet, my cursor is here:

![image](https://cloud.githubusercontent.com/assets/1271146/22146655/51f252ae-defd-11e6-983b-d54a50c7f63e.png)

Is it possible to define within the snippet where the cursor should go?  Ideally, I would end up here:

![image](https://cloud.githubusercontent.com/assets/1271146/22146679/65245bec-defd-11e6-938d-7f218eb052ab.png)

After adding the snippet so that I can immediately add the tags for the post.

**Comment by RickStrahl** [comment]
Yup. ~ syntax like Visual Studio snippets :-) It's one of the things that's on my list. Requires dealing with the selection range that can be a bit tricky and requires some explicit code in the editor.js code.

**Comment by RickStrahl** [comment]
So added this in ad02ec150392dde9b2b90efab84d247edd6ffa72

```
@{
    var file = Path.GetFileNameWithoutExtension(
                                 Model.ActiveDocument.Filename);
    file = StringUtils.FromCamelCase(file);
    file = file.Replace("-"," ");
}---
Title: @file
Timestamp: @DateTime.Now.ToString("MMM dd, yyyy HH:mm")
Tags:
- ~
---
```

The `~` determines where the cursor goes if specified.

It's in 0.2, but this change also requires an update to MM 1.1.18

**Comment by gep13** [comment]
Sweet! Will take this for a spin later.

**Comment by gep13** [comment]
Just got this...

![image](https://cloud.githubusercontent.com/assets/1271146/22177469/11c2a610-e016-11e6-92f9-ba8831dc0547.png)

After updating to 1.1.18, and re-installing the addin.

**Comment by RickStrahl** [comment]
Hmmm... that looks like a different OLD version. 1.0.28. You should be on 1.1.18.

And yes the updated addin requires the newer build.

Can you send me your last error log entries that pertain to that error? I might be able to block off the code that won't run in older versions. I lost track :-)

**Comment by RickStrahl** [comment]
Ok installed older version and re-ran and was able to figure out what was not working - bracketed the new code so  it should work now. Update the addin.

**Comment by gep13** [comment]
I think I see the problem...

Looks like there is an issue with the mm.exe/bat:

![image](https://cloud.githubusercontent.com/assets/1271146/22177486/615d0ada-e016-11e6-9cea-9daa44a39143.png)

If I run mm, I don't get version 1.1.18.

**Comment by RickStrahl** [comment]
Ah - yes. This was due to the switch to the 32 bit version. You probably didn't uninstall the old version when the switch came and Mm is probably still looking at the old \program files\ path.

To fix:

* Delete all the files in Program Files\Markdown Monster
* Remove the system\user path to Program Files\Markdown Monster.

You should end up with only the new version and path pointing at \program files (x86)\Markdown Monster.

That was a sucky thing to have to do but there was no way around that. It was in the update notice and docs to do a full uninstall firs then reinstall, but of course nobody actually reads that :-)

**Comment by gep13** [comment]
Yeah, that did it:

![image](https://cloud.githubusercontent.com/assets/1271146/22177828/f2dab7d0-e01d-11e6-897b-3d66cb7844bf.png)

Yip, I never read that part, just did a `choco upgrade`.  If this needs to happen again, you could add a chocolateyBeforeModify.ps1 script, to do a full uninstall of the application, if currently installed.

**Comment by gep13** [comment]
@RickStrahl ok, now we are getting somewhere.  I am running this:

![image](https://cloud.githubusercontent.com/assets/1271146/22177843/6ea45b5a-e01e-11e6-91db-a45fa73137e4.png)

and this:

![image](https://cloud.githubusercontent.com/assets/1271146/22177845/7a007af6-e01e-11e6-8a6e-95b5ad8687c4.png)

And this is my snippet definition:

![image](https://cloud.githubusercontent.com/assets/1271146/22177849/868d3ab6-e01e-11e6-8533-17f98afdeece.png)

But after adding `bfm` I get this:

![image](https://cloud.githubusercontent.com/assets/1271146/22177852/928f5a24-e01e-11e6-8b7f-4a8ec7439e3a.png)

**Comment by RickStrahl** [comment]
Hmmm... that should work. I just installed 1.1.18 from Choco, unloaded the existing addin and reloaded it and it works for me. You did restart MM after installing the updated addin right? Since addins load in memory a restart is required.

FWIW, there are a bunch of updates coming to the Addin Manager and addin handling in general in the next update (1.1.20 most likely).

![image](https://cloud.githubusercontent.com/assets/1374013/22186840/934300ce-e0a0-11e6-8718-a7e4666cb55e.png)

that will hopefully make updates a little less painful than they are right now.

**Comment by gep13** [comment]
@RickStrahl yip, multiple restarts.  I have this morning uninstalled all addins, and then re-installed them, but the same thing happens.  I wondered if it was something to do with the fact that I was using the vim emulation layer for the editor, but turning the on/off didn't result in any difference either.  The `~` was still output into the document, rather than replacing it with cursor.

I will try again once new MM is published.

**Comment by RickStrahl** [comment]
1.1.19 is out on the Web site (not on Choco yet). I can confirm with 1.1.19 and 0.2.3 installed the ~ is working for me in expansions.

**Comment by RickStrahl** [comment]
The fact that the ~ is still in the output is probably a dead giveaway, you're not running the latest addin as the ~ is replaced even before the cursor movement. 

Is the addin showing up more than once in your Addin list? I fixed the naming to be consistent so it's possible that a new install will not remove the old one.

To fix manually:

* %appdata%\Addins 
* Remove all Snippets looking addins

* %programfiles%\Markdown Monster\Addins
* Remove all Snippets looking addins

**Comment by gep13** [comment]
Nope, only showing up once in Addins list.

I have just cleared out the folders that you suggested.  Updated to latest MM.  Re-installed Snippets addin and still get the same thing.  The ~ is still output, and cursor is not where it is expected to be 😢 

![image](https://cloud.githubusercontent.com/assets/1271146/22266814/4b975e52-e279-11e6-9d52-98625a102ed9.png)

![image](https://cloud.githubusercontent.com/assets/1271146/22266819/548028fa-e279-11e6-85a4-82695da15929.png)

**Comment by RickStrahl** [comment]
I mean on the toolbar. There's an icon - (pen in a box). Is that there more than once?

This one:
![image](https://cloud.githubusercontent.com/assets/1374013/22268624/48d92e18-e22c-11e6-9157-baddb1fda9bb.png)

**Comment by gep13** [comment]
@RickStrahl thanks again! This is now resolved.

**Comment by RickStrahl** [comment]
Thanks for your help and persistance on this.
